name: pompei
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10.9
  - lxml>=4.9.1
  - gdal>=3.4.1
  - h5py
  - requests>=2.28.1
  - geopandas>=0.12.2
  - shapely>=1.8.4
  - pyproj>=3.4.1
  - kornia>=0.6.9
  - pillow>=9.2.0
  - pathlib>=1.0.1
  - torchvision>=0.14.1
  - matplotlib>=3.5.3
  - scipy>=1.9.3
  - geoserver-rest>=2.4.1
  - geoserver-restconfig >=2.0.8
  - fiona>=1.8.22
  - geojson>=2.5.0
  - pip>=22.2.2
  - rasterio>=1.3.10
  - libgdal-jp2openjpeg
  - pip:
    - opencv-python>=4.6.0.66
    - ultralytics>=8.0.50
    - psycopg2-binary>=2.9.5
    - python-dotenv>=1.0.1